<?php

$ignorar_todas = true; // altere para true para ignorar todas as vagas desta fonte

return [
    "1password" => "1password",
    "AfterQuery" => "AfterQuery",
    "atomicsemi" => "atomicsemi",
    "cartesia" => "cartesia",
    "claylabs" => "claylabs",
    "cohere" => "cohere",
    "dash0" => "dash0",
    "deel" => "deel",
    "docker" => "docker",
    "ema" => "ema",
    "etched" => "etched",
    "everai" => "everai",
    "harvey" => "harvey",
    "higharc" => "higharc",
    "hcompany" => "hcompany",
    "hopper" => "hopper",
    "join9am" => "join9am",
    "kota" => "kota",
    "legora" => "legora",
    "neofinancial" => "neofinancial",
    "niramedical" => "niramedical",
    "onebrief" => "onebrief",
    "openai" => "openai",
    "permitflow" => "permitflow",
    "perplexity" => "perplexity",
    "Plaud" => "Plaud",
    "prompt" => "prompt",
    "Juicebox" => "Juicebox",
    "publiccloudgroup" => "publiccloudgroup",
    "reonic" => "reonic",
    "ridealso" => "ridealso",
    "riveron" => "riveron",
    "savvy" => "savvy",
    "sentry" => "sentry",
    "sesame" => "sesame",
    "silver" => "silver",
    "sfcompute" => "sfcompute",
    "skelar" => "skelar",
    "skydio" => "skydio",
    "suno" => "suno",
    "swap" => "swap",
    "upside" => "upside",
    "withpulley" => "withpulley",
];
