name: 🚀 Deploy Mondywork via FTP

# O deploy será disparado automaticamente a cada 'push' na branch main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Sincronizar Arquivos
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Obter código mais recente
      uses: actions/checkout@v4

    - name: 📂 Sincronizar via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp://82.29.199.235
        username: u894432128.mondywork.com
        password: /wXPO3A7ch1R*M8y
        port: 21
        local-dir: ./
        server-dir: ./
        timeout: 120000
        security: loose
        dangerous-allow-unsafe-ssl: true
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/node_modules/**
          .env
          composer.json
          composer.lock
          README.md
          env.txt
          config.local.php
          br/
          dev/
