name: 🚀 Deploy Mondywork via FTP

# O deploy será disparado automaticamente a cada 'push' na branch main
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sincronizar Arquivos
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
    - name: 🚚 Obter código mais recente
      uses: actions/checkout@v4

    - name: 📂 Sincronizar via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./
        server-dir: ./
        timeout: 120000
        security: loose
        dangerous-allow-unsafe-ssl: true
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/node_modules/**
          .env
          composer.json
          composer.lock
          README.md
          env.txt
          config.local.php